// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VehicleUIClient is the client API for VehicleUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VehicleUIClient interface {
	// ListVehicleSpecs returns a list of Vehicle(s) that can be started through the UI.
	ListVehicleSpecs(ctx context.Context, in *ListVehicleSpecsRequest, opts ...grpc.CallOption) (VehicleUI_ListVehicleSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type vehicleUIClient struct {
	cc grpc.ClientConnInterface
}

func NewVehicleUIClient(cc grpc.ClientConnInterface) VehicleUIClient {
	return &vehicleUIClient{cc}
}

func (c *vehicleUIClient) ListVehicleSpecs(ctx context.Context, in *ListVehicleSpecsRequest, opts ...grpc.CallOption) (VehicleUI_ListVehicleSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &VehicleUI_ServiceDesc.Streams[0], "/v1.VehicleUI/ListVehicleSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &vehicleUIListVehicleSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VehicleUI_ListVehicleSpecsClient interface {
	Recv() (*ListVehicleSpecsResponse, error)
	grpc.ClientStream
}

type vehicleUIListVehicleSpecsClient struct {
	grpc.ClientStream
}

func (x *vehicleUIListVehicleSpecsClient) Recv() (*ListVehicleSpecsResponse, error) {
	m := new(ListVehicleSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vehicleUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.VehicleUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VehicleUIServer is the server API for VehicleUI service.
// All implementations must embed UnimplementedVehicleUIServer
// for forward compatibility
type VehicleUIServer interface {
	// ListVehicleSpecs returns a list of Vehicle(s) that can be started through the UI.
	ListVehicleSpecs(*ListVehicleSpecsRequest, VehicleUI_ListVehicleSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedVehicleUIServer()
}

// UnimplementedVehicleUIServer must be embedded to have forward compatible implementations.
type UnimplementedVehicleUIServer struct {
}

func (UnimplementedVehicleUIServer) ListVehicleSpecs(*ListVehicleSpecsRequest, VehicleUI_ListVehicleSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListVehicleSpecs not implemented")
}
func (UnimplementedVehicleUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedVehicleUIServer) mustEmbedUnimplementedVehicleUIServer() {}

// UnsafeVehicleUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VehicleUIServer will
// result in compilation errors.
type UnsafeVehicleUIServer interface {
	mustEmbedUnimplementedVehicleUIServer()
}

func RegisterVehicleUIServer(s grpc.ServiceRegistrar, srv VehicleUIServer) {
	s.RegisterService(&VehicleUI_ServiceDesc, srv)
}

func _VehicleUI_ListVehicleSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListVehicleSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VehicleUIServer).ListVehicleSpecs(m, &vehicleUIListVehicleSpecsServer{stream})
}

type VehicleUI_ListVehicleSpecsServer interface {
	Send(*ListVehicleSpecsResponse) error
	grpc.ServerStream
}

type vehicleUIListVehicleSpecsServer struct {
	grpc.ServerStream
}

func (x *vehicleUIListVehicleSpecsServer) Send(m *ListVehicleSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _VehicleUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehicleUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VehicleUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehicleUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VehicleUI_ServiceDesc is the grpc.ServiceDesc for VehicleUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VehicleUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.VehicleUI",
	HandlerType: (*VehicleUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _VehicleUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListVehicleSpecs",
			Handler:       _VehicleUI_ListVehicleSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vehicle-ui.proto",
}
